mod-dir: /mods
controls:
  input-focus: 225
  input-debug-zoom-in: 86
  input-toggle-debug: 60
  input-debug-print-physics: 64
  input-debug-zoom-out: 87
  input-move-east: 7
  input-move-west: 4
  input-move-south: 22
  input-debug-next-palette: 62
  input-move-north: 26
modded-save-dir: /modded-saves
can-use-debug: true
resolution:
- 1280
- 720
misc: {}
language: english
base-save-dir: /saves
is-v-sync-enabled: false
server-port: 7777
target-fps: 60.0
initial-world: test-world
